service: qb-notification-bot

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14
  httpApi:
    cors: true

functions:
  webhook:
    handler: index.QBbot
    events:
      - httpApi:
          path: /telegraf
          method: post

  cron:
    handler: utils/sendNotifications.run
    timeout: 120
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
