service: qb-notification-bot

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14
  httpApi:
    cors: true

functions:
  echo:
    handler: index.QBbot
    events:
      - httpApi:
          path: /telegraf
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
